included:
  - Demo/Classes

identifier_name:
  excluded:
    - id

line_length:
  ignores_comments: true

file_length:
  ignore_comment_only_lines: true

function_body_length:
  warning: 100
  error: 130

disabled_rules:
  - opening_brace
  - statement_position
  - multiple_closures_with_trailing_closure #swiftUI
  - no_space_in_method_call #swiftUI

function_parameter_count:
  warning: 6
  error: 10

opt_in_rules:
## idiomatic
  - explicit_init #idiomatic
  - function_default_parameter_at_end #idiomatic
  - force_unwrapping #idiomatic
  - convenience_type #idiomatic
  - discouraged_assert #idiomatic
  - fallthrough #idiomatic
  - fatal_error_message #idiomatic
  - file_name_no_space #idiomatic
  - implicitly_unwrapped_optional #idiomatic
  - joined_default_parameter #idiomatic
  - legacy_multiple #idiomatic
  - legacy_random #idiomatic
  - prefer_zero_over_explicit_init #idiomatic
  - redundant_nil_coalescing #idiomatic
  - redundant_type_annotation #idiomatic
  - static_operator #idiomatic
  - unavailable_function #idiomatic
  - untyped_error_in_catch #idiomatic
  - xct_specific_matcher #idiomatic

## lint
  - missing_docs #lint
  - lower_acl_than_parent #lint
  - anyobject_protocol #lint
  - array_init #lint
  - capture_variable #lint
  - discarded_notification_center_observer #lint
  - empty_xctest_method #lint
  - expiring_todo #lint
  - ibinspectable_in_extension #lint
  - identical_operands #lint
  - overridden_super_call #lint
  - private_action #lint
  - private_outlet #lint
  - quick_discouraged_call #lint
  - quick_discouraged_focused_test #lint
  - quick_discouraged_pending_test #lint
  - raw_value_for_camel_cased_codable_enum #lint
  - required_enum_case #lint
  - unused_declaration #lint
  - unused_import #lint
  - yoda_condition #lint
  - private_subject #lint
  - nslocalizedstring_key #lint

## performance
  - contains_over_filter_count #performance
  - contains_over_filter_is_empty #performance
  - contains_over_first_not_nil #performance
  - contains_over_range_nil_comparison #performance
  - empty_collection_literal #performance
  - empty_count #performance
  - empty_string #performance
  - first_where #performance
  - flatmap_over_map_reduce #performance
  - last_where #performance
  - reduce_into #performance
  - sorted_first_last #performance

## style
  - closure_spacing #style
  - multiline_arguments #style
  - vertical_parameter_alignment_on_call #style
  - multiline_literal_brackets #style
  - unneeded_parentheses_in_closure_argument #style
  - modifier_order #style
  - closure_end_indentation #style
  - collection_alignment #style
  - literal_expression_end_indentation #style
  - multiline_function_chains #style
  - multiline_parameters #style
  - number_separator #style
  - operator_usage_whitespace #style
  - optional_enum_case_matching #style
  - prefer_self_type_over_type_of_self # style
  - single_test_class #style
  - vertical_whitespace_closing_braces #style

## metrics
  - enum_case_associated_values_count #metrics // To customize


##### Rules customization
multiline_arguments:
    only_enforce_after_first_closure_on_first_line: true

trailing_whitespace:
    ignores_empty_lines: true

enum_case_associated_values_count:
  - warning:5
  - error: 4
